version: '2.1'
services:
  web:
    image: "phpcensor/php-censor-web:latest"
    ports:
    - "80:80"
    env_file:
    - ./env/phpcensor.env
  worker:
    image: "phpcensor/php-censor-worker:latest"
    env_file:
    - ./env/phpcensor.env
  db:
    image: "postgres"
    user: postgres
    env_file:
    - ./env/database.pgsql.env
  queue:
    image: "schickling/beanstalkd"
    networks:
      default:
        aliases:
        - beanstalk

